document.addEventListener("DOMContentLoader", () => {
  // Vue main app component
  var app = new Vue({
    el: "#app",
    data: {
      reelPos: 0,
      reelHeight: document.querySelectorAll(".reel")[0].offsetHeight,
      spinOneCount: 0,
      spinTwoCount: 0,
      spinThreeCount: 0,
      spinTime: 5,
      img: [
        { id: "pic one", src: "img/3xBAR.png" },
        { id: "pic two", src: "img/BAR.png" },
        { id: "pic three", src: "img/2xBAR.png" },
        { id: "pic four", src: "img/7.png" },
        { id: "pic five", src: "img/Cherry.png" },
      ],
      balance: 100,
      rIsSpinning: false,
      fIsSpinning: true,
      gameMode: "random",
      fMode: "fixed",
      rMode: "random",
      randVis: true,
      lineTop: false,
      lineCenter: false,
      lineBottom: false,
      currentBalance: 5,
      coins: "",
      balanceAlert: false,
      alertTitle: "",
      alertText: "",
      alertButton: "",
      fixVis: false,
      symbolList: [],
      symbolLanding: [],
      cS1: "",
      cS2: "",
      cS3: "",
      cL1: "",
      cL2: "",
      cL3: "",
      payoutsHeaders: [],
      payouts: [
        { combination: "3 Cherry on bottom line", price: 4000 },
        { combination: "3 Cherry on top line", price: 2000 },
        { combination: "3 Cherry on Center line", price: 1000 },
      ],
      currentPosition: [0, 0, 0],
      playerWins: 0,
      newWin: 0,
    },
    methods: {
      fixedSpin: () => {},
      randomSpin: () => {},
      spinOne: () => {},
      spinTwo: () => {},
      spinThree: () => {},
      resetReels: () => {},
      modeSelector: () => {},
      addBalance: () => {},
      fixedCheck: () => {},
      spinEnd: () => {},
      payout: () => {},
    },
  });
});
